name: bm_racing_app
description: "A new Flutter project."
publish_to: "none"
version: 0.2.8+9

environment:
  sdk: ^3.6.0

dependencies:
  awesome_notifications: ^0.10.1
  battery_plus: ^6.2.1
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_blue_plus: ^1.35.2
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.10
  http: ^1.3.0
  intl: ^0.20.0
  keep_screen_on: ^4.0.0
  lottie: ^3.3.1
  package_info_plus: ^8.2.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon/playstore-icon.png"
  min_sdk_version: 23
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - ./data.env
    - assets/loading.json
    - assets/icon/icon_removed_background.png
